#%RAML 1.0 DataType

type: object
properties:
  IDproductAssociated: integer
  BarcodeFullCode: integer
  BarcodeOrigin: string
  BarcodeProviderNumber: integer
  BarcodeProductNumber: integer
  BarcodeControlKey: integer

  