#%RAML 1.0 NamedExample


IDproduct : 1
ProductName : 'Lait Demi-Ecreme GRANDLAIT'
ProductBrand : 'Candia'
ProductPrice : 7.20
ProductDescription : "GrandLait demi-écrémé est idéal pour vous accompagner au..."
ProductWing : 'Frais > Crèmerie > Laits > Lait demi-écrémé'
